
import com.sun.xml.internal.ws.encoding.soap.SOAP12Constants;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author doğukan
 */
public class Main extends javax.swing.JFrame {
private int ddhesap=0;
int alib=0;
int muhatb=0;
int muratb=0;
int mehmetb=0;
int erdemb=0;
private int pdhesap=0;
private int pudhesap=0;
private int ihesap=0;
private int adhesap=0;
private int urhesap=0;
private int tavhesap=0;
private int kuhesap=0;
private int kahesap=0;
private int ozhesap=0;
private int kashesap=0;
private int lahhesap=0;
private int kehesap=0;
private int suhesap=0;
private int  kunhesap=0;
private int dd=0;
private int pd=0;
private int pud=0;
private int i=0;
private int ad=0;
private int ur=0;
private int tav=0;
private int ku=0;
private int ka=0;
private int oz=0;
private int kas=0;
private int lah=0;
private int ke=0;
private int su=0;
private int  kun=0;
private int hesap=0;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        donerdurum = new javax.swing.JCheckBox();
        porsiyondoner = new javax.swing.JCheckBox();
        pustudoner = new javax.swing.JCheckBox();
        ıskender = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        adana = new javax.swing.JCheckBox();
        urfa = new javax.swing.JCheckBox();
        tavuksis = new javax.swing.JCheckBox();
        kuzu = new javax.swing.JCheckBox();
        karisik = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        ozellahmacun = new javax.swing.JCheckBox();
        kasarlılah = new javax.swing.JCheckBox();
        lahmacun = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        kemalpasa = new javax.swing.JCheckBox();
        sutlac = new javax.swing.JCheckBox();
        kunefe = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        tutar = new javax.swing.JTextField();
        onaylı = new javax.swing.JButton();
        pdadet = new javax.swing.JTextField();
        ddadet = new javax.swing.JTextField();
        pudadet = new javax.swing.JTextField();
        ıadet = new javax.swing.JTextField();
        ddart = new javax.swing.JButton();
        pdart = new javax.swing.JButton();
        pudart = new javax.swing.JButton();
        iart = new javax.swing.JButton();
        pdek = new javax.swing.JButton();
        pudek = new javax.swing.JButton();
        iek = new javax.swing.JButton();
        ddek = new javax.swing.JButton();
        adadet = new javax.swing.JTextField();
        tavadet = new javax.swing.JTextField();
        uradet = new javax.swing.JTextField();
        kuzuadet = new javax.swing.JTextField();
        karısıkadet = new javax.swing.JTextField();
        adart = new javax.swing.JButton();
        urart = new javax.swing.JButton();
        tavart = new javax.swing.JButton();
        kuzekle = new javax.swing.JButton();
        karart = new javax.swing.JButton();
        adek = new javax.swing.JButton();
        tavek = new javax.swing.JButton();
        kuzuek = new javax.swing.JButton();
        urek = new javax.swing.JButton();
        karek = new javax.swing.JButton();
        kunart = new javax.swing.JButton();
        lahart = new javax.swing.JButton();
        kasart = new javax.swing.JButton();
        sutart = new javax.swing.JButton();
        ozart = new javax.swing.JButton();
        kemart = new javax.swing.JButton();
        sutek = new javax.swing.JButton();
        ozek = new javax.swing.JButton();
        kasek = new javax.swing.JButton();
        lahek = new javax.swing.JButton();
        kunek = new javax.swing.JButton();
        kemek = new javax.swing.JButton();
        ozad = new javax.swing.JTextField();
        kasad = new javax.swing.JTextField();
        lahad = new javax.swing.JTextField();
        kemad = new javax.swing.JTextField();
        sutad = new javax.swing.JTextField();
        kunad = new javax.swing.JTextField();
        ali = new javax.swing.JButton();
        murat = new javax.swing.JButton();
        erdem = new javax.swing.JButton();
        muhat = new javax.swing.JButton();
        mehmet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENÜ ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ET DÖNER");

        donerdurum.setText("DÖNER DÜRÜM-14 TL");
        donerdurum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donerdurumActionPerformed(evt);
            }
        });

        porsiyondoner.setText("PORSİYON DÖNER-22 TL");
        porsiyondoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porsiyondonerActionPerformed(evt);
            }
        });

        pustudoner.setText("PİLAV ÜSTÜ DÖNER-24 TL");
        pustudoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pustudonerActionPerformed(evt);
            }
        });

        ıskender.setText("İSKENDER-25 TL");
        ıskender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ıskenderActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("KEBAPLAR");

        adana.setText("ADANA KEBAP-22 TL");
        adana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adanaActionPerformed(evt);
            }
        });

        urfa.setText("URFA KEBAP-22 TL");
        urfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urfaActionPerformed(evt);
            }
        });

        tavuksis.setText("TAVUK ŞİŞ-22 TL");
        tavuksis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavuksisActionPerformed(evt);
            }
        });

        kuzu.setText("KUZU ŞİŞ-30  TL");
        kuzu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuzuActionPerformed(evt);
            }
        });

        karisik.setText("KARIŞIK IZGARA-45 TL");
        karisik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karisikActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("LAHMACUN");

        ozellahmacun.setText("ÖZEL LAHMACUN-8 TL");
        ozellahmacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ozellahmacunActionPerformed(evt);
            }
        });

        kasarlılah.setText("KAŞARLI LAHMACUN-8 TL");
        kasarlılah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasarlılahActionPerformed(evt);
            }
        });

        lahmacun.setText("LAHMACUN-6 TL");
        lahmacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lahmacunActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TATLILAR");

        kemalpasa.setText("KEMALPAŞA-6 TL");
        kemalpasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemalpasaActionPerformed(evt);
            }
        });

        sutlac.setText("SÜTLAÇ-6 TL");
        sutlac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sutlacActionPerformed(evt);
            }
        });

        kunefe.setText("KÜNEFE- 12 TL");
        kunefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunefeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TUTAR:");

        tutar.setText("0");

        onaylı.setText("onayla");
        onaylı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylıActionPerformed(evt);
            }
        });

        pdadet.setText("0");

        ddadet.setText("0");

        pudadet.setText("0");

        ıadet.setText("0");

        ddart.setText("+");
        ddart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddartActionPerformed(evt);
            }
        });

        pdart.setText("+");
        pdart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdartActionPerformed(evt);
            }
        });

        pudart.setText("+");
        pudart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pudartActionPerformed(evt);
            }
        });

        iart.setText("+");
        iart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iartActionPerformed(evt);
            }
        });

        pdek.setText("-");
        pdek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdekActionPerformed(evt);
            }
        });

        pudek.setText("-");
        pudek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pudekActionPerformed(evt);
            }
        });

        iek.setText("-");
        iek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iekActionPerformed(evt);
            }
        });

        ddek.setText("-");
        ddek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddekActionPerformed(evt);
            }
        });

        adadet.setText("0");

        tavadet.setText("0");

        uradet.setText("0");

        kuzuadet.setText("0");

        karısıkadet.setText("0");

        adart.setText("+");
        adart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adartActionPerformed(evt);
            }
        });

        urart.setText("+");
        urart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urartActionPerformed(evt);
            }
        });

        tavart.setText("+");
        tavart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavartActionPerformed(evt);
            }
        });

        kuzekle.setText("+");
        kuzekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuzekleActionPerformed(evt);
            }
        });

        karart.setText("+");
        karart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karartActionPerformed(evt);
            }
        });

        adek.setText("-");
        adek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adekActionPerformed(evt);
            }
        });

        tavek.setText("-");
        tavek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavekActionPerformed(evt);
            }
        });

        kuzuek.setText("-");
        kuzuek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuzuekActionPerformed(evt);
            }
        });

        urek.setText("-");
        urek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urekActionPerformed(evt);
            }
        });

        karek.setText("-");
        karek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karekActionPerformed(evt);
            }
        });

        kunart.setText("+");
        kunart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunartActionPerformed(evt);
            }
        });

        lahart.setText("+");
        lahart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lahartActionPerformed(evt);
            }
        });

        kasart.setText("+");
        kasart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasartActionPerformed(evt);
            }
        });

        sutart.setText("+");
        sutart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sutartActionPerformed(evt);
            }
        });

        ozart.setText("+");
        ozart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ozartActionPerformed(evt);
            }
        });

        kemart.setText("+");
        kemart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemartActionPerformed(evt);
            }
        });

        sutek.setText("-");
        sutek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sutekActionPerformed(evt);
            }
        });

        ozek.setText("-");
        ozek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ozekActionPerformed(evt);
            }
        });

        kasek.setText("-");
        kasek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasekActionPerformed(evt);
            }
        });

        lahek.setText("-");
        lahek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lahekActionPerformed(evt);
            }
        });

        kunek.setText("-");
        kunek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kunekActionPerformed(evt);
            }
        });

        kemek.setText("-");
        kemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemekActionPerformed(evt);
            }
        });

        ozad.setText("0");

        kasad.setText("0");

        lahad.setText("0");

        kemad.setText("0");

        sutad.setText("0");

        kunad.setText("0");

        ali.setText("ALİ");
        ali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliActionPerformed(evt);
            }
        });

        murat.setText("MURAT");
        murat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muratActionPerformed(evt);
            }
        });

        erdem.setText("ERDEM");
        erdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erdemActionPerformed(evt);
            }
        });

        muhat.setText("MUHAT");
        muhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muhatActionPerformed(evt);
            }
        });

        mehmet.setText("MEHMET");
        mehmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mehmetActionPerformed(evt);
            }
        });

        jButton1.setText("GÜN SONU RAPORU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ÇIKIŞ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(347, 347, 347))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adana)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(urfa)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kuzu)
                                            .addComponent(tavuksis)))
                                    .addComponent(karisik))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adart)
                                            .addComponent(tavart, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(kuzekle, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(karart, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(adadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(adek)
                                                .addGap(137, 137, 137)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                            .addComponent(karısıkadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addGap(18, 18, 18)
                                                                            .addComponent(karek)
                                                                            .addGap(318, 318, 318)
                                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(kuzuadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(kuzuek)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(kunad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(tavadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(tavek)
                                                                                .addGap(302, 302, 302)
                                                                                .addComponent(sutad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                    .addComponent(kemad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(46, 46, 46)))
                                                            .addComponent(tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(ozellahmacun)
                                                            .addComponent(kasarlılah)
                                                            .addComponent(lahmacun))
                                                        .addGap(48, 48, 48)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(kasart)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(kasad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lahart)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lahad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ozart)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ozad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                                        .addComponent(jButton2))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(urart)
                                        .addGap(18, 18, 18)
                                        .addComponent(uradet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(urek)
                                        .addGap(93, 93, 93)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kunefe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(kunart))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(sutlac)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sutart))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kemalpasa)
                                                .addGap(18, 18, 18)
                                                .addComponent(kemart))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ıskender, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pustudoner)
                                    .addComponent(porsiyondoner)
                                    .addComponent(donerdurum))
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ddek)
                                    .addComponent(pdek)
                                    .addComponent(pudek)
                                    .addComponent(iek)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(621, 621, 621)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kunek)
                                            .addComponent(sutek)
                                            .addComponent(kemek)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(murat)
                                        .addGap(18, 18, 18))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pdart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pdadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ddart)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ddadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pudart)
                                .addComponent(iart))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ıadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pudadet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kasek)
                                .addComponent(lahek)
                                .addComponent(ozek))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ali)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mehmet)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(muhat)
                                    .addComponent(erdem))
                                .addGap(63, 63, 63)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(onaylı, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(donerdurum)
                                .addComponent(ddadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ddek))
                            .addComponent(ddart, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(porsiyondoner)
                            .addComponent(pdart)
                            .addComponent(pdek)
                            .addComponent(pdadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pustudoner)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pudadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pudart)
                                .addComponent(pudek)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ıskender)
                            .addComponent(iart)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ıadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iek)))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ozellahmacun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kasarlılah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lahmacun))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ozart)
                                    .addComponent(ozek)
                                    .addComponent(ozad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kasart)
                                    .addComponent(kasek)
                                    .addComponent(kasad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lahart)
                                    .addComponent(lahek)
                                    .addComponent(lahad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kemalpasa)
                                    .addComponent(kemart)
                                    .addComponent(kemek)
                                    .addComponent(kemad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sutlac)
                                    .addComponent(sutart)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sutad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sutek)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kunefe)
                            .addComponent(kunart)
                            .addComponent(kunek)
                            .addComponent(kunad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(murat)
                                    .addComponent(ali)
                                    .addComponent(erdem))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adana)
                                    .addComponent(adadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adart)
                                    .addComponent(adek))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(muhat)
                                    .addComponent(mehmet)
                                    .addComponent(jButton1))
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urfa)
                            .addComponent(urart)
                            .addComponent(uradet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urek))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tavart)
                                    .addComponent(tavuksis)
                                    .addComponent(tavadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tavek))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(kuzu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kuzuadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kuzuek))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kuzekle)
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(karart)
                                            .addComponent(karisik)
                                            .addComponent(karısıkadet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(karek)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(onaylı, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void donerdurumActionPerformed(java.awt.event.ActionEvent evt) {                                           
       if(donerdurum.isSelected()){
          
     hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kahesap+kehesap+kunhesap+suhesap;
        
              tutar.setText(String.valueOf(hesap));
       }
       
    }                                          

    private void porsiyondonerActionPerformed(java.awt.event.ActionEvent evt) {                                              
if(porsiyondoner.isSelected()){
   hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kahesap+kehesap+kunhesap+suhesap;
 tutar.setText(String.valueOf(hesap));
}
    }                                             

    private void pustudonerActionPerformed(java.awt.event.ActionEvent evt) {                                           
if(pustudoner.isSelected()){
   hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kahesap+kehesap+kunhesap+suhesap;
         
              tutar.setText(String.valueOf(hesap));
}
    }                                          

    private void ıskenderActionPerformed(java.awt.event.ActionEvent evt) {                                         
    if(ıskender.isSelected()){
   hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kahesap+kehesap+kunhesap+suhesap;
          
                tutar.setText(String.valueOf(hesap));
    }
    }                                        

    private void adanaActionPerformed(java.awt.event.ActionEvent evt) {                                      
if(adana.isSelected()){
     hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kahesap+kehesap+kunhesap+suhesap;
          tutar.setText(String.valueOf(hesap));
}

    }                                     

    private void urfaActionPerformed(java.awt.event.ActionEvent evt) {                                     
     
        if(urfa.isSelected()){
       hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
          tutar.setText(String.valueOf(hesap));
}// TODO add your handling code here:
    }                                    

    private void tavuksisActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(tavuksis.isSelected()){
      hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
          tutar.setText(String.valueOf(hesap));
}        // TODO add your handling code here:
    }                                        

    private void kuzuActionPerformed(java.awt.event.ActionEvent evt) {                                     
if(kuzu.isSelected()){
       hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
          tutar.setText(String.valueOf(hesap));
}
   
    }                                    

    private void karisikActionPerformed(java.awt.event.ActionEvent evt) {                                        
    if(karisik.isSelected()){
        hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
              tutar.setText(String.valueOf(hesap));
    }
    }                                       

    private void ozellahmacunActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(ozellahmacun.isSelected()){
            
          hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
              tutar.setText(String.valueOf(hesap));
    }
    }                                            

    private void kasarlılahActionPerformed(java.awt.event.ActionEvent evt) {                                           
         if(kasarlılah.isSelected()){
         hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
              tutar.setText(String.valueOf(hesap));
    }
    }                                          

    private void lahmacunActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(lahmacun.isSelected()){
         hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
              tutar.setText(String.valueOf(hesap));
    }  // TODO add your handling code here:
    }                                        

    private void kemalpasaActionPerformed(java.awt.event.ActionEvent evt) {                                          
      if(kemalpasa.isSelected()){
          hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
              tutar.setText(String.valueOf(hesap));
    }
    }                                         

    private void sutlacActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(sutlac.isSelected()){
          hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;
              tutar.setText(String.valueOf(hesap));
    }
    }                                      

    private void kunefeActionPerformed(java.awt.event.ActionEvent evt) {                                       
         if(kunefe.isSelected()){
         hesap=ddhesap+pdhesap+pudhesap+ihesap+adhesap+urhesap+tavhesap+kuhesap+kahesap+lahhesap+ozhesap+kashesap+kehesap+kunhesap+suhesap;;
              tutar.setText(String.valueOf(hesap));
    }
    }                                      

    private void onaylıActionPerformed(java.awt.event.ActionEvent evt) {                                       
      JOptionPane.showMessageDialog(this,"SİPARİŞİNİZ ONAYLANMIŞTIR");
       pdhesap=0;
 pudhesap=0;
 ihesap=0;
 adhesap=0;
 urhesap=0;
 tavhesap=0;
 kuhesap=0;
 kahesap=0;
 ozhesap=0;
 kashesap=0;
 lahhesap=0;
 kehesap=0;
 suhesap=0;
  kunhesap=0;
 dd=0;
 pd=0;
 pud=0;
 i=0;
 ad=0;
 ur=0;
 tav=0;
ku=0;
 ka=0;
 oz=0;
 kas=0;
 lah=0;
 ke=0;
 su=0;
  kun=0;
hesap=0;
tutar.setText(String.valueOf(0));
ddadet.setText(String.valueOf(0));
pdadet.setText(String.valueOf(0));
pudadet.setText(String.valueOf(0));
ıadet.setText(String.valueOf(0));
adadet.setText(String.valueOf(0));
uradet.setText(String.valueOf(0));
tavadet.setText(String.valueOf(0));
kuzuadet.setText(String.valueOf(0));
karısıkadet.setText(String.valueOf(0));
ozad.setText(String.valueOf(0));
kasad.setText(String.valueOf(0));
lahad.setText(String.valueOf(0));
kemad.setText(String.valueOf(0));
sutad.setText(String.valueOf(0));
kunad.setText(String.valueOf(0));
        
    }                                      

    private void ddartActionPerformed(java.awt.event.ActionEvent evt) {                                      
     dd=Integer.valueOf(ddadet.getText());
     dd+=1;
     ddadet.setText(String.valueOf(dd));
      ddhesap=14*dd;
          
        donerdurumActionPerformed(evt);
    }                                     

    private void ddekActionPerformed(java.awt.event.ActionEvent evt) {                                     
dd=Integer.valueOf(ddadet.getText());
     dd-=1;
     ddadet.setText(String.valueOf(dd));
      ddhesap=14*dd;
          
        donerdurumActionPerformed(evt);
    }                                    

    private void pdartActionPerformed(java.awt.event.ActionEvent evt) {                                      
       pd=Integer.valueOf(pdadet.getText());
     pd+=1;
     pdadet.setText(String.valueOf(pd));
      pdhesap=22*pd;
          
        porsiyondonerActionPerformed(evt); // TODO add your handling code here:
    }                                     

    private void pdekActionPerformed(java.awt.event.ActionEvent evt) {                                     
       pd=Integer.valueOf(pdadet.getText());
     pd-=1;
     pdadet.setText(String.valueOf(pd));
      pdhesap=22*pd;
          
        porsiyondonerActionPerformed(evt);       // TODO add your handling code here:
    }                                    

    private void pudartActionPerformed(java.awt.event.ActionEvent evt) {                                       
           pud=Integer.valueOf(pudadet.getText());
     pud+=1;
     pudadet.setText(String.valueOf(pud));
      pudhesap=24*pud;
        pustudonerActionPerformed(evt);
          // TODO add your handling code here:
    }                                      

    private void pudekActionPerformed(java.awt.event.ActionEvent evt) {                                      
         pud=Integer.valueOf(pudadet.getText());
     pud-=1;
     pudadet.setText(String.valueOf(pud));
      pudhesap=24*pud;
        pustudonerActionPerformed(evt);        // TODO add your handling code here:
    }                                     

    private void iartActionPerformed(java.awt.event.ActionEvent evt) {                                     
         i=Integer.valueOf(ıadet.getText());
     i+=1;
     ıadet.setText(String.valueOf(i));
      ihesap=25*i;
        ıskenderActionPerformed(evt);        // TODO add your handling code here:
    }                                    

    private void iekActionPerformed(java.awt.event.ActionEvent evt) {                                    
  i=Integer.valueOf(ıadet.getText());
     i-=1;
     ıadet.setText(String.valueOf(i));
      ihesap=25*i;
        ıskenderActionPerformed(evt);          // TODO add your handling code here:
    }                                   

    private void adartActionPerformed(java.awt.event.ActionEvent evt) {                                      
ad=Integer.valueOf(adadet.getText());
ad+=1;
adadet.setText(String.valueOf(ad));
adhesap=22*ad;
        adanaActionPerformed(evt);
    }                                     

    private void adekActionPerformed(java.awt.event.ActionEvent evt) {                                     
ad=Integer.valueOf(adadet.getText());
ad-=1;
adadet.setText(String.valueOf(ad));
adhesap=22*ad;
        adanaActionPerformed(evt);        // TODO add your handling code here:
    }                                    

    private void urartActionPerformed(java.awt.event.ActionEvent evt) {                                      
ur=Integer.valueOf(uradet.getText());
ur+=1;
uradet.setText(String.valueOf(ur));
urhesap=22*ur;
        urfaActionPerformed(evt);        // TODO add your handling code here:
    }                                     

    private void urekActionPerformed(java.awt.event.ActionEvent evt) {                                     
ur=Integer.valueOf(uradet.getText());
ur-=1;
uradet.setText(String.valueOf(ur));
urhesap=22*ur;
        urfaActionPerformed(evt);
        // TODO add your handling code here:
    }                                    

    private void tavartActionPerformed(java.awt.event.ActionEvent evt) {                                       
tav=Integer.valueOf(tavadet.getText());
tav+=1;
tavadet.setText(String.valueOf(tav));
tavhesap=22*tav;
        tavuksisActionPerformed(evt);     // TODO add your handling code here:
    }                                      

    private void tavekActionPerformed(java.awt.event.ActionEvent evt) {                                      
tav=Integer.valueOf(tavadet.getText());
tav-=1;
tavadet.setText(String.valueOf(tav));
tavhesap=22*tav;
        tavuksisActionPerformed(evt);        // TODO add your handling code here:
    }                                     

    private void kuzekleActionPerformed(java.awt.event.ActionEvent evt) {                                        
 ku=Integer.valueOf(kuzuadet.getText());
ku+=1;
kuzuadet.setText(String.valueOf(ku));
kuhesap=30*ku;
        kuzuActionPerformed(evt);
    }                                       

    private void kuzuekActionPerformed(java.awt.event.ActionEvent evt) {                                       
 ku=Integer.valueOf(kuzuadet.getText());
ku-=1;
kuzuadet.setText(String.valueOf(ku));
kuhesap=30*ku;    
        kuzuActionPerformed(evt);// TODO add your handling code here:
    }                                      

    private void karartActionPerformed(java.awt.event.ActionEvent evt) {                                       
      ka=Integer.valueOf(karısıkadet.getText());
      ka++;
      karısıkadet.setText(String.valueOf(ka));
      kahesap=45*ka;
              karisikActionPerformed(evt);

    }                                      

    private void karekActionPerformed(java.awt.event.ActionEvent evt) {                                      
      ka=Integer.valueOf(karısıkadet.getText());
      ka-=1;
      karısıkadet.setText(String.valueOf(ka));
      kahesap=45*ka;
        karisikActionPerformed(evt);
    }                                     

    private void ozartActionPerformed(java.awt.event.ActionEvent evt) {                                      
       oz=Integer.valueOf(ozad.getText());
      oz+=1;
      ozad.setText(String.valueOf(oz));
      ozhesap=8*oz;
              ozellahmacunActionPerformed(evt);
  // TODO add your handling code here:
    }                                     

    private void ozekActionPerformed(java.awt.event.ActionEvent evt) {                                     
    oz=Integer.valueOf(ozad.getText());
      oz-=1;
      ozad.setText(String.valueOf(oz));
      ozhesap=8*oz;
              ozellahmacunActionPerformed(evt);        // TODO add your handling code here:
    }                                    

    private void kasartActionPerformed(java.awt.event.ActionEvent evt) {                                       
            kas=Integer.valueOf(kasad.getText());
      kas+=1;
      kasad.setText(String.valueOf(kas));
      kashesap=8*kas;
        kasarlılahActionPerformed(evt);
    }                                      

    private void kasekActionPerformed(java.awt.event.ActionEvent evt) {                                      
                kas=Integer.valueOf(kasad.getText());
      kas-=1;
      kasad.setText(String.valueOf(kas));
      kashesap=8*kas;
        kasarlılahActionPerformed(evt);
    }                                     

    private void lahartActionPerformed(java.awt.event.ActionEvent evt) {                                       
                lah=Integer.valueOf(lahad.getText());
      lah+=1;
      lahad.setText(String.valueOf(lah));
      lahhesap=6*lah;
        lahmacunActionPerformed(evt);
    }                                      

    private void lahekActionPerformed(java.awt.event.ActionEvent evt) {                                      
                 lah=Integer.valueOf(lahad.getText());
      lah-=1;
      lahad.setText(String.valueOf(lah));
      lahhesap=6*lah;
        lahmacunActionPerformed(evt);
    }                                     

    private void kemartActionPerformed(java.awt.event.ActionEvent evt) {                                       
             ke=Integer.valueOf(kemad.getText());
      ke+=1;
      kemad.setText(String.valueOf(ke));
     kehesap=6*ke;
        kemalpasaActionPerformed(evt);   // TODO add your handling code here:
    }                                      

    private void kemekActionPerformed(java.awt.event.ActionEvent evt) {                                      
             ke=Integer.valueOf(kemad.getText());
      ke-=1;
      kemad.setText(String.valueOf(ke));
     kehesap=6*ke;
        kemalpasaActionPerformed(evt);    // TODO add your handling code here:
    }                                     

    private void sutartActionPerformed(java.awt.event.ActionEvent evt) {                                       
             su=Integer.valueOf(sutad.getText());
      su+=1;
      sutad.setText(String.valueOf(su));
     suhesap=6*su;
        sutlacActionPerformed(evt);   // TODO add your handling code here:
    }                                      

    private void sutekActionPerformed(java.awt.event.ActionEvent evt) {                                      
          su=Integer.valueOf(sutad.getText());
      su-=1;
      sutad.setText(String.valueOf(su));
     suhesap=6*su;
        sutlacActionPerformed(evt);// TODO add your handling code here:
    }                                     

    private void kunartActionPerformed(java.awt.event.ActionEvent evt) {                                       
      kun=Integer.valueOf(kunad.getText());
     kun+=1;
      kunad.setText(String.valueOf(kun));
     kunhesap=12*kun;
        kunefeActionPerformed(evt);   // TODO add your handling code here:
    }                                      

    private void kunekActionPerformed(java.awt.event.ActionEvent evt) {                                      
  kun=Integer.valueOf(kunad.getText());
     kun-=1;
      kunad.setText(String.valueOf(kun));
     kunhesap=12*kun;
        kunefeActionPerformed(evt);      // TODO add your handling code here:
    }                                     

    private void muratActionPerformed(java.awt.event.ActionEvent evt) {                                      
 
muratb+=hesap;// TODO add your handling code here:
    }                                     

    private void aliActionPerformed(java.awt.event.ActionEvent evt) {                                    

alib+=hesap;// TODO add your handling code here:
    }                                   

    private void erdemActionPerformed(java.awt.event.ActionEvent evt) {                                      

erdemb+=hesap;
// TODO add your handling code here:
    }                                     

    private void mehmetActionPerformed(java.awt.event.ActionEvent evt) {                                       

mehmetb+=hesap;// TODO add your handling code here:
    }                                      

    private void muhatActionPerformed(java.awt.event.ActionEvent evt) {                                      

muhatb+=hesap;

    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
     Rapor rapor=new Rapor();
     rapor.yazdir(muratb, alib, erdemb, mehmetb, muhatb);
     rapor.setVisible(true);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
System.exit(0);        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField adadet;
    private javax.swing.JCheckBox adana;
    private javax.swing.JButton adart;
    private javax.swing.JButton adek;
    private javax.swing.JButton ali;
    private javax.swing.JTextField ddadet;
    private javax.swing.JButton ddart;
    private javax.swing.JButton ddek;
    private javax.swing.JCheckBox donerdurum;
    private javax.swing.JButton erdem;
    private javax.swing.JButton iart;
    private javax.swing.JButton iek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton karart;
    private javax.swing.JButton karek;
    private javax.swing.JCheckBox karisik;
    private javax.swing.JTextField karısıkadet;
    private javax.swing.JTextField kasad;
    private javax.swing.JCheckBox kasarlılah;
    private javax.swing.JButton kasart;
    private javax.swing.JButton kasek;
    private javax.swing.JTextField kemad;
    private javax.swing.JCheckBox kemalpasa;
    private javax.swing.JButton kemart;
    private javax.swing.JButton kemek;
    private javax.swing.JTextField kunad;
    private javax.swing.JButton kunart;
    private javax.swing.JCheckBox kunefe;
    private javax.swing.JButton kunek;
    private javax.swing.JButton kuzekle;
    private javax.swing.JCheckBox kuzu;
    private javax.swing.JTextField kuzuadet;
    private javax.swing.JButton kuzuek;
    private javax.swing.JTextField lahad;
    private javax.swing.JButton lahart;
    private javax.swing.JButton lahek;
    private javax.swing.JCheckBox lahmacun;
    private javax.swing.JButton mehmet;
    private javax.swing.JButton muhat;
    private javax.swing.JButton murat;
    private javax.swing.JButton onaylı;
    private javax.swing.JTextField ozad;
    private javax.swing.JButton ozart;
    private javax.swing.JButton ozek;
    private javax.swing.JCheckBox ozellahmacun;
    private javax.swing.JTextField pdadet;
    private javax.swing.JButton pdart;
    private javax.swing.JButton pdek;
    private javax.swing.JCheckBox porsiyondoner;
    private javax.swing.JTextField pudadet;
    private javax.swing.JButton pudart;
    private javax.swing.JButton pudek;
    private javax.swing.JCheckBox pustudoner;
    private javax.swing.JTextField sutad;
    private javax.swing.JButton sutart;
    private javax.swing.JButton sutek;
    private javax.swing.JCheckBox sutlac;
    private javax.swing.JTextField tavadet;
    private javax.swing.JButton tavart;
    private javax.swing.JButton tavek;
    private javax.swing.JCheckBox tavuksis;
    private javax.swing.JTextField tutar;
    private javax.swing.JTextField uradet;
    private javax.swing.JButton urart;
    private javax.swing.JButton urek;
    private javax.swing.JCheckBox urfa;
    private javax.swing.JTextField ıadet;
    private javax.swing.JCheckBox ıskender;
    // End of variables declaration                   
}
